export const movies = [
  {
    adult: false,
    backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg",
    id: 447365,
    title: "Guardians of the Galaxy Vol. 3",
    original_language: "en",
    original_title: "Guardians of the Galaxy Vol. 3",
    overview:
      "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    poster_path: "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    media_type: "movie",
    genre_ids: [878, 12, 28],
    popularity: 6145.684,
    release_date: "2023-05-03",
    video: false,
    vote_average: 8.155,
    vote_count: 2783,
  },
  {
    adult: false,
    backdrop_path: "/woJbg7ZqidhpvqFGGMRhWQNoxwa.jpg",
    id: 667538,
    title: "Transformers: Rise of the Beasts",
    original_language: "en",
    original_title: "Transformers: Rise of the Beasts",
    overview:
      "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
    poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 878],
    popularity: 1971.248,
    release_date: "2023-06-06",
    video: false,
    vote_average: 7.269,
    vote_count: 633,
  },
  {
    adult: false,
    backdrop_path: "/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg",
    id: 335977,
    title: "Indiana Jones and the Dial of Destiny",
    original_language: "en",
    original_title: "Indiana Jones and the Dial of Destiny",
    overview:
      "Finding himself in a new era, approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
    poster_path: "/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
    media_type: "movie",
    genre_ids: [12, 28, 14],
    popularity: 399.616,
    release_date: "2023-06-28",
    video: false,
    vote_average: 6.632,
    vote_count: 599,
  },
  {
    adult: false,
    backdrop_path: "/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
    id: 575264,
    title: "Mission: Impossible - Dead Reckoning Part One",
    original_language: "en",
    original_title: "Mission: Impossible - Dead Reckoning Part One",
    overview:
      "Ethan Hunt and his IMF team embark on their most dangerous mission yet: To track down a terrifying new weapon that threatens all of humanity before it falls into the wrong hands. With control of the future and the world's fate at stake and dark forces from Ethan's past closing in, a deadly race around the globe begins. Confronted by a mysterious, all-powerful enemy, Ethan must consider that nothing can matter more than his mission – not even the lives of those he cares about most.",
    poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 53],
    popularity: 672.196,
    release_date: "2023-07-08",
    video: false,
    vote_average: 8.022,
    vote_count: 89,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    id: 385687,
    title: "Fast X",
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    media_type: "movie",
    genre_ids: [28, 80, 53],
    popularity: 2583.164,
    release_date: "2023-05-17",
    video: false,
    vote_average: 7.364,
    vote_count: 2592,
  },
  {
    adult: false,
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 16, 878],
    popularity: 1307.679,
    release_date: "2023-05-31",
    video: false,
    vote_average: 8.508,
    vote_count: 2161,
  },
  {
    adult: false,
    backdrop_path: "/57clBMPX25NNO6nmDw3TV3zQaQE.jpg",
    id: 114472,
    name: "Secret Invasion",
    original_language: "en",
    original_name: "Secret Invasion",
    overview:
      "Nick Fury and Talos discover a faction of shapeshifting Skrulls who have been infiltrating Earth for years.",
    poster_path: "/3rINdUPSy9AklJg74jWHOyUXuZd.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 10759],
    popularity: 2054.878,
    first_air_date: "2023-06-21",
    vote_average: 7.929,
    vote_count: 252,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/wRxLAw4l17LqiFcPLkobriPTZAw.jpg",
    id: 697843,
    title: "Extraction 2",
    original_language: "en",
    original_title: "Extraction 2",
    overview:
      "Tasked with extracting a family who is at the mercy of a Georgian gangster, Tyler Rake infiltrates one of the world's deadliest prisons in order to save them. But when the extraction gets hot, and the gangster dies in the heat of battle, his equally ruthless brother tracks down Rake and his team to Vienna, in order to get revenge.",
    poster_path: "/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
    media_type: "movie",
    genre_ids: [28, 53],
    popularity: 1001.428,
    release_date: "2023-06-09",
    video: false,
    vote_average: 7.583,
    vote_count: 1271,
  },
  {
    adult: false,
    backdrop_path: "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
    id: 502356,
    title: "The Super Mario Bros. Movie",
    original_language: "en",
    original_title: "The Super Mario Bros. Movie",
    overview:
      "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    media_type: "movie",
    genre_ids: [16, 10751, 12, 14, 35],
    popularity: 1169.751,
    release_date: "2023-04-05",
    video: false,
    vote_average: 7.803,
    vote_count: 5535,
  },
  {
    adult: false,
    backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
    id: 603692,
    title: "John Wick: Chapter 4",
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    media_type: "movie",
    genre_ids: [28, 53, 80],
    popularity: 1241.495,
    release_date: "2023-03-22",
    video: false,
    vote_average: 7.859,
    vote_count: 3607,
  },
  {
    adult: false,
    backdrop_path: "/oqP1qEZccq5AD9TVTIaO6IGUj7o.jpg",
    id: 455476,
    title: "Knights of the Zodiac",
    original_language: "en",
    original_title: "Knights of the Zodiac",
    overview:
      "When a headstrong street orphan, Seiya, in search of his abducted sister unwittingly taps into hidden powers, he discovers he might be the only person alive who can protect a reincarnated goddess, sent to watch over humanity. Can he let his past go and embrace his destiny to become a Knight of the Zodiac?",
    poster_path: "/tBiUXvCqz34GDeuY7jK14QQdtat.jpg",
    media_type: "movie",
    genre_ids: [14, 28, 12],
    popularity: 2459.93,
    release_date: "2023-04-27",
    video: false,
    vote_average: 6.488,
    vote_count: 409,
  },
  {
    adult: false,
    backdrop_path: "/foGkPxpw9h8zln81j63mix5B7m8.jpg",
    id: 71912,
    name: "The Witcher",
    original_language: "en",
    original_name: "The Witcher",
    overview:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    poster_path: "/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
    media_type: "tv",
    genre_ids: [18, 10759, 10765],
    popularity: 958.73,
    first_air_date: "2019-12-20",
    vote_average: 8.165,
    vote_count: 4851,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/gmECX1DvFgdUPjtio2zaL8BPYPu.jpg",
    id: 95479,
    name: "Jujutsu Kaisen",
    original_language: "ja",
    original_name: "呪術廻戦",
    overview:
      "Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a classmate who has been attacked by curses, he eats the finger of Ryomen Sukuna, taking the curse into his own soul. From then on, he shares one body with Ryomen Sukuna. Guided by the most powerful of sorcerers, Satoru Gojo, Itadori is admitted to Tokyo Jujutsu High School, an organization that fights the curses... and thus begins the heroic tale of a boy who became a curse to exorcise a curse, a life from which he could never turn back.",
    poster_path: "/3yFHMtdhriig4sm1w8oMQfA2gFN.jpg",
    media_type: "tv",
    genre_ids: [16, 10759, 10765],
    popularity: 483.322,
    first_air_date: "2020-10-03",
    vote_average: 8.55,
    vote_count: 2626,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/cSYLX73WskxCgvpN3MtRkYUSj1T.jpg",
    id: 976573,
    title: "Elemental",
    original_language: "en",
    original_title: "Elemental",
    overview:
      "In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.",
    poster_path: "/8riWcADI1ekEiBguVB9vkilhiQm.jpg",
    media_type: "movie",
    genre_ids: [16, 35, 10751, 14, 10749],
    popularity: 1050.704,
    release_date: "2023-06-14",
    video: false,
    vote_average: 7.46,
    vote_count: 414,
  },
  {
    adult: false,
    backdrop_path: "/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
    id: 76600,
    title: "Avatar: The Way of Water",
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    media_type: "movie",
    genre_ids: [878, 12, 28],
    popularity: 647.513,
    release_date: "2022-12-14",
    video: false,
    vote_average: 7.675,
    vote_count: 9091,
  },
  {
    adult: false,
    backdrop_path: "/llZSAx6YW0y9tV4iMKmbUBNh70I.jpg",
    id: 346698,
    title: "Barbie",
    original_language: "en",
    original_title: "Barbie",
    overview:
      "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    poster_path: "/cgYg04miVQUAG2FKk3amSnnHzOp.jpg",
    media_type: "movie",
    genre_ids: [35, 12, 14],
    popularity: 836.072,
    release_date: "2023-07-19",
    video: false,
    vote_average: 7.5,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/4QpKxH614YFIsmiIBVUbsnG2H8w.jpg",
    id: 961323,
    title: "Nimona",
    original_language: "en",
    original_title: "Nimona",
    overview:
      "A knight framed for a tragic crime teams with a scrappy, shape-shifting teen to prove his innocence.",
    poster_path: "/2NQljeavtfl22207D1kxLpa4LS3.jpg",
    media_type: "movie",
    genre_ids: [16, 28, 12, 14],
    popularity: 404.044,
    release_date: "2023-06-23",
    video: false,
    vote_average: 7.863,
    vote_count: 204,
  },
  {
    adult: false,
    backdrop_path: "/yF1eOkaYvwiORauRCPWznV9xVvi.jpg",
    id: 298618,
    title: "The Flash",
    original_language: "en",
    original_title: "The Flash",
    overview:
      "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
    poster_path: "/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg",
    media_type: "movie",
    genre_ids: [878, 28, 12],
    popularity: 654.961,
    release_date: "2023-06-13",
    video: false,
    vote_average: 6.693,
    vote_count: 780,
  },
  {
    adult: false,
    backdrop_path: "/fjWcAbHRxCSR4kLGvsPEhNjR2ts.jpg",
    id: 921636,
    title: "The Out-Laws",
    original_language: "en",
    original_title: "The Out-Laws",
    overview:
      "A straight-laced bank manager is about to marry the love of his life. When his bank is held up by infamous Ghost Bandits during his wedding week, he believes his future in-laws who just arrived in town, are the infamous Out-Laws.",
    poster_path: "/5dliMQ2ODbGNoq0hlefdnuXQxMw.jpg",
    media_type: "movie",
    genre_ids: [10749, 28, 35],
    popularity: 310.999,
    release_date: "2023-07-07",
    video: false,
    vote_average: 6.42,
    vote_count: 119,
  },
  {
    adult: false,
    backdrop_path: "/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg",
    id: 125988,
    name: "Silo",
    original_language: "en",
    original_name: "Silo",
    overview:
      "In a ruined and toxic future, a community exists in a giant underground silo that plunges hundreds of stories deep. There, men and women live in a society full of regulations they believe are meant to protect them.",
    poster_path: "/zBx1X06G1OlndbXTCZI13FECNz2.jpg",
    media_type: "tv",
    genre_ids: [10765, 18],
    popularity: 524.949,
    first_air_date: "2023-05-04",
    vote_average: 8.343,
    vote_count: 348,
    origin_country: ["US", "GB"],
  },

  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 1128514,
    original_language: "en",
    original_title: "Big Sur Gay Porn",
    overview:
      "Cult filmmaker Tom DeSimone (Reform School Girls; Erotikus: A History of the Gay Movie) revisits the production of a lost gay film and resurrects youthful adventures on the California coast. From the creators of Raw! Uncut! Video!.",
    popularity: 110.653,
    poster_path: "/d8yVOYquXejIkrGFrIVzX610R4N.jpg",
    release_date: "2023-06-16",
    title: "Big Sur Gay Porn",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [99, 10402],
    id: 682878,
    original_language: "de",
    original_title: "Sound of Freedom",
    overview: "",
    popularity: 123.015,
    poster_path: "/btWbiLuDvTvSESuP8DhYLjGK8Ee.jpg",
    release_date: "2019-01-01",
    title: "Sound of Freedom",
    video: false,
    vote_average: 6,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/qiCECQ4DjocDVXLakUja3FVMWka.jpg",
    genre_ids: [28, 12, 99],
    id: 1127808,
    original_language: "es",
    original_title: "Spider-Man: 20 años de películas",
    overview: "",
    popularity: 70.855,
    poster_path: "/wGQyDEgTVEjyHKBV7eurj37zfkJ.jpg",
    release_date: "2023-06-05",
    title: "Spider-Man: 20 años de películas",
    video: false,
    vote_average: 4.8,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/ww3OoIaQxRO4o78YJdVlmKIsikm.jpg",
    genre_ids: [99],
    id: 1128717,
    original_language: "en",
    original_title: "Unknown: The Lost Pyramid",
    overview:
      "Egyptian archeologists dig into history, discovering tombs and artifacts over 4,000 years old as they search for a buried pyramid in this documentary.",
    popularity: 59.768,
    poster_path: "/5KV7WxGjF5O5fhBJnjNME4jkJC7.jpg",
    release_date: "2023-07-03",
    title: "Unknown: The Lost Pyramid",
    video: false,
    vote_average: 7.4,
    vote_count: 13,
  },
  {
    adult: false,
    backdrop_path: "/1OkHpWLrsNtsbu4rw87FJi26PkN.jpg",
    genre_ids: [99, 10770],
    id: 988170,
    original_language: "en",
    original_title:
      "Soul of a Nation Presents: Sound of Freedom – A Juneteenth Celebration",
    overview:
      "The special brings together a mix of live performances and conversations with some of music’s biggest stars to highlight the contributions of Black Americans through jazz, gospel, hip-hop and more.",
    popularity: 97,
    poster_path: "/vjMtoQW7XC1rLhk7YLmRuGId7Wk.jpg",
    release_date: "2022-06-17",
    title:
      "Soul of a Nation Presents: Sound of Freedom – A Juneteenth Celebration",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/3OYdLI1I8lZKkzu3AgEm3iHyvip.jpg",
    genre_ids: [99, 10402],
    id: 1134865,
    original_language: "en",
    original_title: "Wham!",
    overview:
      "Through archival interviews and footage, George Michael and Andrew Ridgeley relive the arc of their Wham! career, from 70s best buds to 80s pop icons.",
    popularity: 57.805,
    poster_path: "/e7drGW0r92hORioVOigC7hWpVMm.jpg",
    release_date: "2023-06-27",
    title: "Wham!",
    video: false,
    vote_average: 7.1,
    vote_count: 15,
  },
  {
    adult: false,
    backdrop_path: "/AfS7QTuDNIySoqcGyg9YFel3X3P.jpg",
    genre_ids: [99],
    id: 736759,
    original_language: "en",
    original_title: "Making The Witcher",
    overview:
      "Journey into the extraordinary world of \"The Witcher\" — from casting the roles to Jaskier's catchy song — in this behind-the-scenes look at the series. Go behind the monsters, the ballads and every bit of magic that went into bringing The Witcher's Continent to life.",
    popularity: 57.721,
    poster_path: "/zYnwBAUPQn5WmurROH1ravCC6Wp.jpg",
    release_date: "2020-08-26",
    title: "Making The Witcher",
    video: false,
    vote_average: 7.1,
    vote_count: 66,
  },
  {
    adult: false,
    backdrop_path: "/it7ue9ag1bxtlssJZC6gCAN17S0.jpg",
    genre_ids: [99],
    id: 1131562,
    original_language: "es",
    original_title: "Fenómeno Twin Melody",
    overview: "",
    popularity: 69.121,
    poster_path: "/2HlrhnJO1vzpXDujHXU8P9GMjUN.jpg",
    release_date: "2023-05-26",
    title: "Fenómeno Twin Melody",
    video: false,
    vote_average: 2,
    vote_count: 1,
  },
  {
    adult: false,
    backdrop_path: "/8rft8A9nH43IReybFtYt21ezfMK.jpg",
    genre_ids: [99],
    id: 899082,
    original_language: "en",
    original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    popularity: 61.768,
    poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    release_date: "2022-01-01",
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    video: false,
    vote_average: 7.3,
    vote_count: 2967,
  },
  {
    adult: false,
    backdrop_path: "/sGE6N1vJjxZLkOJEXdIOqTslxuL.jpg",
    genre_ids: [99],
    id: 1087040,
    original_language: "en",
    original_title: "Money Shot: The Pornhub Story",
    overview:
      "Featuring interviews with performers, activists and past employees, this documentary offers a deep dive into the successes and scandals of Pornhub.",
    popularity: 55.623,
    poster_path: "/kpTqWqLYcf1uErnx5VXLah4EWJZ.jpg",
    release_date: "2023-03-15",
    title: "Money Shot: The Pornhub Story",
    video: false,
    vote_average: 5.8,
    vote_count: 230,
  },
  {
    adult: false,
    backdrop_path: "/i6ZQKIiQKHmcAKxbe4Tk5AcLugY.jpg",
    genre_ids: [99],
    id: 1114901,
    original_language: "en",
    original_title: "Take Care of Maya",
    overview:
      "When Jack and Beata Kowalski are wrongfully accused of child abuse after their 10-year-old daughter Maya visits the ER, a nightmare unfolds.",
    popularity: 48.246,
    poster_path: "/ktpoqsz2O5xz8SPxc358YXmmzHU.jpg",
    release_date: "2023-06-10",
    title: "Take Care of Maya",
    video: false,
    vote_average: 7.7,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: "/ifGs4hSnqTCFmhJqCGe5Ec0cTe5.jpg",
    genre_ids: [99],
    id: 1025169,
    original_language: "th",
    original_title: "13 หมูป่า: เรื่องเล่าจากในถ้ำ",
    overview:
      "In this compelling documentary, members of the Thai youth soccer team tell their stories of getting trapped in Tham Luang Cave in 2018 — and surviving.",
    popularity: 39.759,
    poster_path: "/jQb1UjOdc2DsU4SqDebrVH8dHvC.jpg",
    release_date: "2022-10-05",
    title: "The Trapped 13: How We Survived The Thai Cave",
    video: false,
    vote_average: 6.9,
    vote_count: 35,
  },
  {
    adult: false,
    backdrop_path: "/baUvUzOK94ZxiC0iRHR20PwsiNU.jpg",
    genre_ids: [99],
    id: 1128718,
    original_language: "en",
    original_title: "Unknown: Killer Robots",
    overview:
      "What happens when a machine makes life-or-death decisions? This documentary explores the dangers of artificial intelligence in military application.",
    popularity: 65.307,
    poster_path: "/lZ61VGpdRiMUlptBucnjBc64Wrj.jpg",
    release_date: "2023-07-10",
    title: "Unknown: Killer Robots",
    video: false,
    vote_average: 6.3,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/uO6ZUez70Twan92pqoV60T9kiGH.jpg",
    genre_ids: [99],
    id: 440249,
    original_language: "en",
    original_title: "After Porn Ends 2",
    overview:
      "After Porn Ends 2 picks up where its predecessor left off and not only turns back the clock to meet the oldest living stars in adult film's history, but goes in depth with some of Its most current retirees and juxtaposes their experiences in a life after porn. Delving deeper into society's ongoing stigmas of race, misogyny, and the reality of decreasing opportunities for these former VHS box cover stars. For some, their careers in adult entertainment is accepted proudly and without regret. In fact, it seems to have proven to be the pathway to their current happiness and inner peace. For others, however, a career in porn has proven to be a conduit to certain despair as they struggle to find a way to bury their past and emerge with a new career or calling.",
    popularity: 38.276,
    poster_path: "/rfItXrtDGILwsCdmgVxX79phFuI.jpg",
    release_date: "2017-03-28",
    title: "After Porn Ends 2",
    video: false,
    vote_average: 5.3,
    vote_count: 213,
  },
  {
    adult: false,
    backdrop_path: "/5cnbmWWnzC2L0CbOYZDeCWbHHJP.jpg",
    genre_ids: [99],
    id: 324558,
    original_language: "en",
    original_title: "X-Rated: The Greatest Adult Movies of All Time",
    overview:
      "The evolution of adult cinema through the most influential films in history, a journey that begins in the 1970s and ends nowadays. An in-depth analysis of the success of the most prestigious erotic films, their impact on industry and society, and their influence on cinema and contemporary culture.",
    popularity: 39.917,
    poster_path: "/uYzHkzZPp84B7nHOKaJZWjyGFUL.jpg",
    release_date: "2015-02-06",
    title: "X-Rated: The Greatest Adult Movies of All Time",
    video: false,
    vote_average: 6.2,
    vote_count: 157,
  },
  {
    adult: false,
    backdrop_path: "/bV7eAcBrYb57PwjpQ2ODT6VyFPd.jpg",
    genre_ids: [99],
    id: 318256,
    original_language: "en",
    original_title: "Hot Girls Wanted",
    overview:
      "A first-ever look at the realities of the professional “amateur” porn world and the steady stream of 18-to-19-year old girls entering into it.",
    popularity: 37.758,
    poster_path: "/75ot83QOkc02vujyzmIbumQCU6Y.jpg",
    release_date: "2015-05-29",
    title: "Hot Girls Wanted",
    video: false,
    vote_average: 6,
    vote_count: 543,
  },
  {
    adult: false,
    backdrop_path: "/chKGRT7RjkHWlU0hRFQeJMx2Bra.jpg",
    genre_ids: [18, 99],
    id: 511679,
    original_language: "es",
    original_title: "Héctor El Father: Conocerás la verdad",
    overview:
      'This autobiography of Hector Delgado runs from his childhood to become one of the greatest exponents of the urban genre, but the results of that life did not please him and led him to try to take his life  .After being victim of a firefight at a service station in Aguada, a city hall in Puerto Rico, he stopped earning at least two hundred American dollars for presentation and being "devout of Jesus"',
    popularity: 28.064,
    poster_path: "/tkP0FzEivLxsUYt8BlaL8Sh7ceY.jpg",
    release_date: "2018-03-22",
    title: "Héctor El Father: Conocerás la verdad",
    video: false,
    vote_average: 7.8,
    vote_count: 95,
  },
  {
    adult: false,
    backdrop_path: "/bywThfrqhK4PUPMPhkrkDAKF0yd.jpg",
    genre_ids: [99, 10770],
    id: 228088,
    original_language: "fr",
    original_title: "De Superman à Spider-Man: L'aventure des super-héros",
    overview:
      "The historical saga of American superheroes. Born in the period between the Great Depression and the World War II to combat the hobgoblins of the modern world, these mutant human beings with superhuman powers colonized the funny papers, radio dramas, television and films, to become a truly national industry in the United States: they gave expression to the fears and obsessions of the twentieth century and bolstered American ideals.",
    popularity: 23.09,
    poster_path: "/b6760qS8pEb3elWp4e7KPQsGliC.jpg",
    release_date: "2001-12-23",
    title: "Once Upon a Time: The Super Heroes",
    video: false,
    vote_average: 6.7,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: "/tObVe1R7JnO3VXBvAOWTEPmmegu.jpg",
    genre_ids: [99],
    id: 961651,
    original_language: "en",
    original_title: "Spider-Man: All Roads Lead to No Way Home",
    overview:
      "Join our hosts JB Smoove and Martin Starr for a celebration of 20 years of Spider-Man™ movies!  From the original Sam Raimi trilogy to Marc Webb’s “amazing” movies to the latest trio from Director Jon Watts, we will take viewers through the stars, the stunts and action, the villains and heroes and an homage to Stan Lee, along with a few surprises. Find your favourite Spider-Man pajamas and prepare to swing through the past two decades of Spider-Man at the movies!",
    popularity: 39.228,
    poster_path: "/e2LLmI5wKIrWGAy9Of3yyWu7Szn.jpg",
    release_date: "2022-05-03",
    title: "Spider-Man: All Roads Lead to No Way Home",
    video: false,
    vote_average: 6.8,
    vote_count: 46,
  },
  {
    adult: false,
    backdrop_path: "/64urMQXrdPVA8hr4PJayN7s5M8l.jpg",
    genre_ids: [99],
    id: 1133922,
    original_language: "de",
    original_title: "Eldorado – Alles, was die Nazis hassen",
    overview:
      "A glittery nightclub in 1920s Berlin becomes a haven for the queer community in this documentary exploring the freedoms lost amid Hitler’s rise to power.",
    popularity: 29.674,
    poster_path: "/hRxLEqRj1qEqxvfpQLtZKANmqDU.jpg",
    release_date: "2023-06-28",
    title: "Eldorado: Everything the Nazis Hate",
    video: false,
    vote_average: 7.7,
    vote_count: 18,
  },
];
